-- MySQL Script generated by MySQL Workbench
-- Sun May 16 19:57:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema auto_insurance
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema auto_insurance
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auto_insurance` DEFAULT CHARACTER SET utf8 ;
USE `auto_insurance` ;

-- -----------------------------------------------------
-- Table `auto_insurance`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_insurance`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `middleName` VARCHAR(50) NOT NULL,
  `birthDay` DATETIME NOT NULL,
  `passportSeries` VARCHAR(4) NOT NULL,
  `passportNumber` VARCHAR(6) NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `photo` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_insurance`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_insurance`.`car` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vin` VARCHAR(17) NOT NULL,
  `brand` VARCHAR(50) NOT NULL,
  `yearRelease` DATETIME NOT NULL,
  `registrationPlate` VARCHAR(9) NOT NULL,
  `power` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_insurance`.`insurance_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_insurance`.`insurance_service` (
  `serviceId` INT NOT NULL AUTO_INCREMENT,
  `service` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`serviceId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_insurance`.`price_policy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_insurance`.`price_policy` (
  `idPrice` INT NOT NULL AUTO_INCREMENT,
  `price` INT NOT NULL,
  PRIMARY KEY (`idPrice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_insurance`.`policy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_insurance`.`policy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `policySeries` VARCHAR(3) NOT NULL,
  `policyNumber` VARCHAR(10) NOT NULL,
  `insuranceSum` INT NOT NULL,
  `beginning` DATETIME NOT NULL,
  `ending` DATETIME NOT NULL,
  `idService` INT NOT NULL,
  `idPrice` INT NOT NULL,
  `idCar` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idCar_idx` (`idCar` ASC) VISIBLE,
  INDEX `idService_idx` (`idService` ASC) VISIBLE,
  INDEX `idPrice_idx` (`idPrice` ASC) VISIBLE,
  CONSTRAINT `id_car`
    FOREIGN KEY (`idCar`)
    REFERENCES `auto_insurance`.`car` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_service`
    FOREIGN KEY (`idService`)
    REFERENCES `auto_insurance`.`insurance_service` (`serviceId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_price`
    FOREIGN KEY (`idPrice`)
    REFERENCES `auto_insurance`.`price_policy` (`idPrice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_insurance`.`contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_insurance`.`contract` (
  `contractNumber` INT NOT NULL AUTO_INCREMENT,
  `dateContract` DATETIME NOT NULL,
  `idClient` INT NOT NULL,
  `idPolicy` INT NOT NULL,
  PRIMARY KEY (`contractNumber`),
  INDEX `idClient_idx` (`idClient` ASC) VISIBLE,
  INDEX `idPolicy_idx` (`idPolicy` ASC) VISIBLE,
  CONSTRAINT `id_client`
    FOREIGN KEY (`idClient`)
    REFERENCES `auto_insurance`.`client` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_policy`
    FOREIGN KEY (`idPolicy`)
    REFERENCES `auto_insurance`.`policy` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_insurance`.`car_driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_insurance`.`car_driver` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `middleName` VARCHAR(50) NOT NULL,
  `licenseSeries` VARCHAR(4) NOT NULL,
  `licenseNumber` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_insurance`.`policy_driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_insurance`.`policy_driver` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idPolicyLink` INT NOT NULL,
  `idCarDriverLink` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idPolicy_idx` (`idPolicyLink` ASC) VISIBLE,
  INDEX `idCarDriver_idx` (`idCarDriverLink` ASC) VISIBLE,
  CONSTRAINT `id_policy_link`
    FOREIGN KEY (`idPolicyLink`)
    REFERENCES `auto_insurance`.`policy` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_car_driver_link`
    FOREIGN KEY (`idCarDriverLink`)
    REFERENCES `auto_insurance`.`car_driver` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auto_insurance`.`insurance_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auto_insurance`.`insurance_event` (
  `accidentId` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `amountPayment` INT NOT NULL,
  `idPolicy` INT NOT NULL,
  `idService` INT NOT NULL,
  PRIMARY KEY (`accidentId`),
  INDEX `idPolicy_idx` (`idPolicy` ASC) VISIBLE,
  INDEX `idService_idx` (`idService` ASC) VISIBLE,
  CONSTRAINT `ie_id_policy`
    FOREIGN KEY (`idPolicy`)
    REFERENCES `auto_insurance`.`policy` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ie_id_service`
    FOREIGN KEY (`idService`)
    REFERENCES `auto_insurance`.`insurance_service` (`serviceId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
